CREATE TABLE withdraw (
    website_id VARCHAR PRIMARY KEY NOT NULL UNIQUE,
    discord_id BIGINT NOT NULL UNIQUE,
    interaction_token VARCHAR NOT NULL UNIQUE,
    start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_check BOOLEAN NOT NULL DEFAULT FALSE 
)